apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      serviceAccountName: knox-sa
      containers:
      - name: go
        image: prateeknandle/go:v24
        ports:
        - containerPort: 8080